export const GET_CAPACITIES = "GET_CAPACITIES";
export const DELETE_CAPACITY = "DELETE_CAPACITY";
export const ADD_CAPACITY = "ADD_CAPACITY";
export const GET_ERRORS = "GET_ERRORS";
export const GET_CAPACITY = "GET_CAPACITY";
export const CLEAR_CAPACITY_CLOSE_MODAL = "CLEAR_CAPACITY_CLOSE_MODAL";
export const UPDATE_CAPACITY = "UPDATE_CAPACITY";
